### ISSUE TITLE
Persist Favorite and Read Status Across Sessions

### ISSUE THREAD

**Issue by chhakuli123** [chhakuli123/in-box-pro#10]
### User Story: 
As a user, I want my favorite and read status to be saved across sessions so that I don’t lose track of important emails.
### Tasks:
- [x] Use localStorage to store and retrieve the states of favorite and read emails.
 - [x] Ensure that the email list and detail components fetch the correct data from localStorage when the app is loaded.
- [x] Test the implementation to make sure the statuses persist after refreshing or reopening the app.

**Comment by chhakuli123** [comment]
closed with https://github.com/chhakuli123/in-box-pro/pull/13
