### ISSUE TITLE
Add Pagination Support to the Email List

### ISSUE THREAD

**Issue by chhakuli123** [chhakuli123/in-box-pro#9]
### User Story:
 As a user, I want to navigate through pages of emails if the list is long so I can see all my emails.
### Tasks:
- [x] Add logic to fetch paginated email data from the API (GET https://flipkart-email-mock.now.sh/?page=<pageNumber>).
- [x] Create a pagination component that allows navigation between pages (e.g., "Previous" and "Next" buttons).
- [x] Update the email list component to display paginated results when the user navigates between pages.

**Comment by chhakuli123** [comment]
closed with https://github.com/chhakuli123/in-box-pro/pull/13
